### PR TITLE
Fixed the message check for $offer

### PR DESCRIPTION
**Pull request by JaonHax**
No longer case-sensitive, ignores spacing, basically fixes most of the problems people had with the check. Or at least it should. Haven't been able to test myself, so maybe you should before merging.

### CODE REVIEW

**Comment by JaonHax** [comment]
People putting `Buy @user` or `buy  @user`, basically fixing stuff for mobile users because a mention automatically adds a space on mobile and autocaps happens, too.

**Comment by Gelbpunkt** [comment]
I'd do that with `.lower()` only.
I think removing multiple whitespaces is a bit too much, but if so, I'd do use `re.replace`.

Apart from that, the code does not work as intended, this should be `True`.
screenshot_20190123-221704

**Comment by JaonHax** [comment]
I think the code's a bit wrong, there. Try `valid_chars.__contains__` rather than `valid_chars.contains`. From what I've read it should work.

**Comment by JaonHax** [comment]
Oof nevermind didn't notice the underline

**Comment by JaonHax** [comment]
Ah, I think I know how to fix that. Try `str(filter...`

**Comment by numbermaniac** [comment]
Not quite, `filter` returns a generator so it won't be equal to a string, and `str()` won't work either.

```py
>>> str(filter("abc".__contains__,"abacus"))
'<filter object at 0x100a93630>'
>>> list(filter("abc".__contains__,"abacus"))
['a', 'b', 'a', 'c']
```

**Comment by JaonHax** [comment]
Okay. Thanks! I'll close this and make a different one with only the .lower() cuz that's the main problem anyway. Sorry!

**Comment by Gelbpunkt** [comment]
@JaonHax 
In my view, this may be what you want, but using regexes is a bit too much effort for this task
screenshot_20190124-144723

**Comment by JaonHax** [comment]
Yeah, both programming- and usage-wise.

**Pull request closed without merging**
