### PR TITLE
why not?

### PR DESCRIPTION
**Pull request by starspritechippy**
This is emoji 🇫

### CODE REVIEW

**Comment by Gelbpunkt** [comment]
oh uhm I didn't mean to merge this if it was a Hacktoberfest PR @maxx0911

**Comment by starspritechippy** [comment]
Hey, it's just one little reaction added, nothing significant, we don't need that counted toward hacktoberfest.

**Comment by Gelbpunkt** [comment]
What about your other PRs?

**Comment by starspritechippy** [comment]
I'd want those merged for Hacktober, yes. But please have a look at them regardless, I want to correct any mistakes.

**Pull request merged**
