### PR TITLE
don't add unnecessary prefixes

### PR DESCRIPTION
**Pull request by Jashanlol**

### CODE REVIEW

**Comment by Gelbpunkt** [comment]
Hmm... A nice attempt.

1) Don't waste memory on `bot.all_guild_ids`. Create `all_guild_ids` once in the function itself and let gc handle it.

2) Make the if-else so it's just a single `if`.

3) This won't work. We have a figure a better way. As the bot isn't logged in yet, it has no `bot.guilds`...

**Comment by Diniboy1123** [comment]
Why is that `all_guild_ids` even necessary?

I'd put the whole thing into a separate task which I call from there and it'd firstly wait until the bot is ready (`await bot.wait_until_ready()`) then iterate over the **guilds** list and for each guild.id I would load the prefixes into memory.

Also a considerable but not necessary addition to make a global check which either returns False always (except for bot owners) or returns the result of `bot.is_ready()` and it should be removed after the bot is ready and the bot has all the prefixes loaded. This way we can avoid using commands during the boot process, so there are less issues.

**Comment by Gelbpunkt** [comment]
Good idea. That way people won't be surprised if music doesn't work because the Queue has no started work yet

**Comment by Gelbpunkt** [comment]
We'll work out our own, I guess

**Pull request closed without merging**
