### PR TITLE
cooldown reset on command timeout

### PR DESCRIPTION
**Pull request by starspritechippy**
I'm not too sure if you agree with resetting the `$child` and `$familyevent`, but I added it for now. If you don't agree, please mention that and I'll follow up with another commit.

### CODE REVIEW

**Comment by starspritechippy** [comment]
I'm not too sure what's up with the commit diff showing more additions and deletions than there actually are. But I can assure, other than the timeout command cooldown reset I didn't change anything.

**Comment by Gelbpunkt** [comment]
https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/error_handler/__init__.py#L163
https://github.com/Gelbpunkt/IdleRPG/blob/v4/cogs/error_handler/__init__.py#L223
It already gets reset on timeout, just noticed that :)

**Comment by starspritechippy** [comment]
Well, not exactly.
Everytime there is a wait_for with a Timeout, it's always in a try-except block, meaning it will never be caught in the error handler, just in the except block.
But the cooldown reset in the others, I should have seen earlier.

**Comment by Gelbpunkt** [comment]
Please update your PR to remove the already resetting cases and rebase on the current v4. Maybe that fixes the diff

**Comment by starspritechippy** [comment]
I'll do that

**Comment by starspritechippy** [comment]
Let me just get this straight, just to make sure before I go reverting changes:
if a `await ctx.confirm()` returns `False`, it will also raise `NoChoice` and the error handler will reset cooldown. **But**, when there's an `asyncio.TimeoutError`, it's in its own try-except block, and the error handler will not reset cooldown, right?

**Comment by Gelbpunkt** [comment]
Exactly :)

**Comment by starspritechippy** [comment]
Alright, that should be it. Hope I got everything now 😅 
I'm so used to using the GitHub website to edit files that making multiple file changes in one commit (using git, updating branches in the local repo, pushing to my own fork, etc.) is new to me. Pretty sure it shows 😬

**Comment by starspritechippy** [comment]
image

**Pull request merged**
