### PR TITLE
fixes to child and shop

### PR DESCRIPTION
**Pull request by Jashanlol**
add `msg.channel.id == ctx.channel.id` to both wait_for checks in the child command
fix shop to escape markdown on seller name to stop from breaking shop

### CODE REVIEW

**Comment by Gelbpunkt** [comment]
Wouldn't `clean_charname` also work with a `replace("\`", "\\\`")`?

**Comment by Jashanlol** [comment]
I was going to do that but ` is not the only markdown a user can use. Your formatted would also mess up if they used **

**Comment by Jashanlol** [comment]
Like I said I like to make my features idiot proof XD

**Comment by Gelbpunkt** [comment]
Mhm. Can we please keep the converter attached to the Cog so we can re-use it?

**Comment by Jashanlol** [comment]
I will do it in the morning

**Comment by Jashanlol** [comment]
Refactored ✅

**Comment by Gelbpunkt** [comment]
merged in 3.4

**Pull request closed without merging**
