### PR TITLE
Show armor for shields and damage for swords

### PR DESCRIPTION
**Pull request by Toaster192**
Edited some of the parts where there would be a 0.0 for damage or armor because of different item types (useless information)
Not really tested (but shouldn't contain breaking changes).
Also if you plan on adding more itemtypes that have both stats then this would have to get reworked.

### CODE REVIEW

**Comment by Gelbpunkt** [comment]
Yes, we plan a whole redesign in the next major release including maps, extensions, races, new combat system, quests, abilities and more!
We will rework weapons to multiple types with minimum, maximum and critical damage. Therefore, we will most likely throw away all current code, but I dislike merging this PR because I prefer the current format.

Would be open to discuss this, though.

**Comment by Toaster192** [comment]
Understandable if a redesign is on the way.

I believe showing stats that can't have any other value (0 armor for swords) is not only unnecessary but also unwanted as it makes some messages like the inventory hard to read. 

But I admit this is arguable and obviously is up to you guys to decide.

Thanks either way for making this bot and I'll be looking forward to the new version.

**Comment by Gelbpunkt** [comment]
You got a point there - I'll let @Diniboy1123 decide, he has the final word, as I'm unsure. I do understand the changes and your intention, it's a matter of personal preferences here

**Comment by Gelbpunkt** [comment]
@Toaster192 would you mind redoing this PR for the dev branch? I won't merge into master, that branch is frozen until we're done with v3.4

**Comment by Toaster192** [comment]
Sure, I'm on it

**Pull request closed without merging**
