### PR TITLE
adventure.py: Confirm before cancelling adventure

### LINKED ISSUE #145: Suggestion: Adventure Cancellation Confirmation Message
**Is your feature request related to a problem? Please describe.**
I accidentally cancelled a level 11 adventure which was 10 minutes from completing thinking the command was universal (I'm not sure how to describe it).  I was curious about the battle command but didn't want to initiate anything and instinctively typed $cancel and ended up sabotaging my mission.  I forgot that idling caused most things to cancel themselves.

**Describe the solution you'd like**
A confirmation message asking something along the lines of "Are you sure you want to cancel your adventure?  y/n".

**Describe alternatives you've considered**
Just something similar to confirmation messages when you attempt to sell equipped gear.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by numbermaniac**
Fixes #145.

### CODE REVIEW

**Review by Gelbpunkt — CHANGES_REQUESTED** [review]
Please use gettext . `_("String")`

**Comment by numbermaniac** [comment]
Oh yeah, I forgot about that, sorry. Should be fixed.

**Comment by Gelbpunkt** [comment]
Seems you also hit the wrong branch

**Comment by numbermaniac** [comment]
I noticed the other PR #147 went to the 3.6 branch instead of 4 so I wasn't sure which was preferred.

**Comment by numbermaniac** [comment]
#154

**Pull request closed without merging**
