### PR TITLE
Fix shop cmd pagination

### PR DESCRIPTION
**Pull request by Jashanlol**
Add check `user == ctx.author` so only the author can paginate

### CODE REVIEW

**Comment by Jashanlol** [comment]
shop paginate check fix

**Comment by Gelbpunkt** [comment]
This is a great issue. Can you please re-open to the v3.4 branch? Also, the `msgcheck` below is missing that author check as well Oo

**Comment by numbermaniac** [comment]
GitHub might give you a drop down button to switch the branch in the PR, not sure how well it works though.

**Comment by Gelbpunkt** [comment]
Lol it worked haha

**Comment by numbermaniac** [comment]
Oh nice lol, I thought only the author of the PR would be able to do that :joy:

**Pull request merged**
