### PR TITLE
Fix adventure success calculation

### LINKED ISSUE #204: bug in $adventures success rate calculation
**Describe the bug**
When my luck is set to 2, $adventures displays a lower success chance than when my luck is set to 0. 

**To Reproduce**
Set luck to 2, run $adventures, check success rates 
Set luck to 0, run $adventures, check success rates

**Expected behavior**
Higher success rate at 2 luck than 0 luck.

**Screenshots**
0 luck: 714579C6-EDE8-44CB-8A20-9F7065AE3AD3
2 luck:
1959B341-1209-4A5B-8592-C1B1D39E7853

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13 I think?
 - Browser Discord app

**Additional context**

### PR DESCRIPTION
**Pull request by numbermaniac**
Fixes #204.

Note that the only fault with this is that if the chance of success is negative, multiplying it by the luck is only going to make it *more* negative.

### CODE REVIEW

**Comment by Gelbpunkt** [comment]
Can you use `luck = -luck` if the operation is negative?

**Comment by numbermaniac** [comment]
That won't always work either. The minimum could end up being larger than the maximum, for some conditions.

**Comment by Gelbpunkt** [comment]
Actually just gotta divide when it's e.g. `-100%` and luck is 1.5, divide by it. Will be `-50%`.

**Comment by Gelbpunkt** [comment]
Fixed in e1df666

**Pull request closed without merging**
